let mon = document.querySelector('#mon')
let sun = document.querySelector('#sun')
let darmod = document.querySelector('.darck')
let container = document.querySelector('.container')
let headeconta = document.querySelector('.header__conta')
let main = document.querySelector('.main')
let mainsection = document.querySelector('.main__section')
let showing = document.querySelector('.header__showing')
let icon = document.querySelector('#icon')
let book = document.querySelector('.book')
let text = document.querySelector('.main__section__text')
let selcti = document.querySelector('.main__section ')
let headerText = document.querySelector('.header__text ')
let headerInput= document.querySelector('.header__input ')
let sarche= document.querySelector('#sarche ')
const eldiv = findElement('#offcanvasRight')
const blek = findElement('#offcanvasRightLabel')
const offcanvasHeader = findElement('.offcanvas-header')
const infoTaxt = findElement('#info__taxt')
const infoInner = document.querySelector('.info__inner')
const infoInner2 = document.querySelector('.info__inner2')
const infoInner4 = document.querySelector('.info__inner3')
const infoInner3 = document.querySelector('.info__inner4')
const infoInner5 = document.querySelector('.info__inner5')
let them = 'light';


darmod.addEventListener('click', () => {
    if (them === "dark") {
        them = 'light';
        document.body.style.background = "#fff"
        document.body.className = ('body-dark1')
        main.style.background = "#e5e5e5"
        container.style.background = "#fff"
        offcanvasHeader.style.background = "#F8FAFD"
        headeconta.style.background = "#fff"
        mainsection.style.background = "#fff"
        headerInput.style.background = "#f8fafd"
        sarche.style.background = "#f8fafd"
        showing.style.background = "#fff"
        eldiv.style.background = "#fff"
        book.style.color = "#000"
        sarche.style.color = "#000"
        headerText.style.color = "#000"
        text.style.color = "#000"
        blek.style.color = "#000"
        infoInner.style.color = "#000"
        infoInner2.style.color = "#000"
        infoInner3.style.color = "#000"
        infoInner4.style.color = "#000"
        infoInner5.style.color = "#000"
        infoTaxt.style.color = "#000"
        mon.style.display = 'block'
        sun.style.display = 'none'
        icon.src = "./img/icock.svg"
        selcti.style.boxShadow = "0px 3px 2px rgb(0 0 0 / 10%)"
    } else if (them == "light") {
        them = 'dark';
        document.body.style.background = "#212529"
        main.style.background = "rgb(48, 48, 48)"
        container.style.background = "#212529"
        headeconta.style.background = "#212529"
        mainsection.style.background = "#212529"
        eldiv.style.background = "#212529"
        offcanvasHeader.style.background ="rgb(48, 48, 48)"
        headerInput.style.background = "rgb(48, 48, 48)"
        sarche.style.background = "rgb(48, 48, 48)"
        showing.style.background = "#212529"
        document.body.className = ('body-dark')
        mon.style.display = 'none'
        sun.style.display = 'block'
        icon.src = "./img/Group2.png"
        book.style.color = "#fff"
        headerText.style.color = "#fff"
        sarche.style.color = "#fff"
        blek.style.color = "#fff"
        infoInner.style.color = "#fff"
        infoInner2.style.color = "#fff"
        infoInner3.style.color = "#fff"
        infoInner.style.color = "#fff"
        infoInner.style.color = "#fff"
        infoInner.style.color = "#fff"
        infoTaxt.style.color = "#fff"
        text.style.color = "#fff"
        selcti.style.boxShadow = "0px 3px 2px rgba(255, 255, 255)"
    }
})